# This is a sample config.yaml file

database:
  host: localhost
  port: 5432
  username: myuser
  password: mypassword
  dbname: mydatabase

api_key: abc123xyz789

logging:
  level: INFO
  format: json

app:
  debug: true
  max_requests: 100

